In [1]:
import torch 
a = 5
tensor = torch.arange(a)
tensor.shape, tensor

(torch.Size([5]), tensor([0, 1, 2, 3, 4]))

In [2]:
grid = torch.stack(torch.meshgrid(tensor, tensor, indexing= 'ij'))
grid.shape , grid 

(torch.Size([2, 5, 5]),
 tensor([[[0, 0, 0, 0, 0],
          [1, 1, 1, 1, 1],
          [2, 2, 2, 2, 2],
          [3, 3, 3, 3, 3],
          [4, 4, 4, 4, 4]],
 
         [[0, 1, 2, 3, 4],
          [0, 1, 2, 3, 4],
          [0, 1, 2, 3, 4],
          [0, 1, 2, 3, 4],
          [0, 1, 2, 3, 4]]]))

In [3]:
tens = torch.sign(grid)
tensor = tens.view(2, -1
                   )
tensor.shape

torch.Size([2, 25])

In [6]:
tensor

tensor([[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1],
        [0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
         1]])

In [17]:
ten_t = tensor[:, -1]

In [18]:
ten_t.shape

torch.Size([2])

In [19]:
ten_t

tensor([1, 1])

In [ ]:
q = torch.tensor(grid)
k = torch.tensor(grid)
sim = torch.einsum('b h i , b h j  -> b h i j', q, k)
sim.shape 