In [1]:
import torch 

In [3]:
# Cộng, trừ, nhân, chia tensors
a = torch.tensor([[1, 2, 3]])
b = torch.tensor([[4, 5, 6]])

add_result = a + b
sub_result = a - b
mul_result = a * b
div_result = a / b

print("Addition:", add_result)
print("Subtraction:", sub_result)
print("Multiplication:", mul_result)
print("Division:", div_result)


Addition: tensor([[5, 7, 9]])
Subtraction: tensor([[-3, -3, -3]])
Multiplication: tensor([[ 4, 10, 18]])
Division: tensor([[0.2500, 0.4000, 0.5000]])


In [5]:
c = torch.randint(0, 5, size=(2,3))
c.shape , c

(torch.Size([2, 3]),
 tensor([[1, 1, 1],
         [1, 2, 1]]))

In [9]:
d = torch.randint(0, 5, size=(2,3))
s = d* c

In [10]:
s, s.shape

(tensor([[2, 0, 4],
         [3, 4, 3]]),
 torch.Size([2, 3]))

In [2]:
import torch

# Tạo tensors
tensor1 = torch.tensor([[1, 2], [3, 4], [5, 6]])  # 3x2
tensor2 = torch.tensor([[7, 8, 9], [10, 11, 12]])  # 2x3

# Chuyển vị tensor thứ hai
tensor2_transposed = tensor2.T  # 3x2

# Nhân ma trận
result = torch.matmul(tensor1, tensor2)

print(result)


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [3]:
tensor1.shape , tensor2.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [4]:
tensor1 , tensor2

(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 tensor([[ 7,  8,  9],
         [10, 11, 12]]))