Phương thức Optinal và List

In [40]:
from typing import Optional , List

In [41]:
def func(x: Optional[int]) -> Optional[str]:
    if x is not None:
        return str(x)
    else:
        return None

# Trong ví dụ trên, hàm func nhận vào một tham số 
# x có thể là kiểu int hoặc None, và trả về một giá trị kiểu str hoặc None.

In [42]:
def get_lengths(strings: List[str]) -> List[int]:
    return [len(s) for s in strings]

# Trong ví dụ trên, hàm get_lengths nhận vào một danh sách các chuỗi strings
# và trả về một danh sách các số nguyên int tương ứng với độ dài của mỗi chuỗi.

Phương thức default và deque

In [43]:
from collections import defaultdict
d = defaultdict(int)  # Mặc định giá trị là 0 cho các khóa mới
d['key_not_exist'] # Không gây ra KeyError, trả về 0


0

In [44]:
from collections import deque
q = deque([1, 2, 3])
q.appendleft(0)  # Thêm vào đầu deque
q.pop()  ,q        # Xóa phần tử cuối cùng


(3, deque([0, 1, 2]))

In [1]:
import torch

# Example bounding boxes with format [x_min, y_min, x_max, y_max]
boxes1 = torch.tensor([
    [10, 20, 30, 40],  # Box 1
    [50, 60, 70, 80],  # Box 2
    [90, 100, 110, 120]  # Box 3
])

# Using boxes1[:, None, :2] to extract the top-left coordinates (x_min, y_min)
top_left_coordinates = boxes1[:, None, :2]


In [46]:
boxes = boxes1 

In [47]:
boxes1 = boxes1[:, :]
boxes1

tensor([[ 10,  20,  30,  40],
        [ 50,  60,  70,  80],
        [ 90, 100, 110, 120]])

In [48]:
boxes2 = boxes[:, :,]
boxes

tensor([[ 10,  20,  30,  40],
        [ 50,  60,  70,  80],
        [ 90, 100, 110, 120]])

In [49]:
boxes3 = boxes1[:,None,:]
boxes3 , boxes3.shape

(tensor([[[ 10,  20,  30,  40]],
 
         [[ 50,  60,  70,  80]],
 
         [[ 90, 100, 110, 120]]]),
 torch.Size([3, 1, 4]))

In [52]:
boxes6 = boxes1[:, None, :1]
boxes6 , boxes6.shape

(tensor([[[10]],
 
         [[50]],
 
         [[90]]]),
 torch.Size([3, 1, 1]))

In [50]:
boxes4 = boxes1[:, None , :2]
boxes4.shape

torch.Size([3, 1, 2])

In [51]:
boxes5 = boxes1[:, None, :3]
boxes5 , boxes5.shape

(tensor([[[ 10,  20,  30]],
 
         [[ 50,  60,  70]],
 
         [[ 90, 100, 110]]]),
 torch.Size([3, 1, 3]))

In [2]:
boxes7 = boxes1[:, None , -2:]
boxes7 , boxes7.shape

(tensor([[[ 30,  40]],
 
         [[ 70,  80]],
 
         [[110, 120]]]),
 torch.Size([3, 1, 2]))

In [55]:
boxes8 = boxes1[:,None, 0]
boxes8 , boxes8.shape

(tensor([[10],
         [50],
         [90]]),
 torch.Size([3, 1]))

In [56]:
a = torch.tensor([1,2,3,4])

In [66]:
b = a[:]
b

tensor([1, 2, 3, 4])

In [15]:
import torch 
a = torch.tensor([[1, 2,3,4,5],
                 [2,2,2,2,6]])
a

tensor([[1, 2, 3, 4, 5],
        [2, 2, 2, 2, 6]])

In [17]:
b = a [:, 0::3] # lấy theo chuồi cuối cùng bắt đầu ở vị trí 0 với sải bước = 3 
b.shape , b

(torch.Size([2, 2]),
 tensor([[1, 4],
         [2, 2]]))

In [25]:
a.shape 

torch.Size([2, 4])

In [30]:
b = torch.tensor([[1, 2, 3 ,4]])
b.shape

torch.Size([1, 4])

In [31]:
c = a*b
c.shape , c

(torch.Size([2, 4]),
 tensor([[ 1,  4,  9, 16],
         [ 2,  4,  6,  8]]))

In [35]:
# Giả sử mỗi tensor một chiều sau đại diện cho một tọa độ của hộp giới hạn:
x_min = torch.tensor([[1, 3, 5]])
y_min = torch.tensor([[2, 4, 6]])
x_max = torch.tensor([[7, 9, 11]])
y_max = torch.tensor([[8, 10, 12]])

# Khi ghép chúng lại theo chiều 1, ta được:
boxes = torch.stack([x_min, y_min, x_max, y_max], -1)
boxes, boxes.shape ,x_max.shape
# Output sẽ là:
# tensor([[ 1,  2,  7,  8],
#         [ 3,  4,  9, 10],
#         [ 5,  6, 11, 12]])

(tensor([[[ 1,  2,  7,  8],
          [ 3,  4,  9, 10],
          [ 5,  6, 11, 12]]]),
 torch.Size([1, 3, 4]),
 torch.Size([1, 3]))

In [36]:
boxes.shape 
boxes = boxes [:, -1, :] # lấy ra giá trị cuối cùng của chiều thứ 2 
boxes.shape , boxes 

(torch.Size([1, 4]), tensor([[ 5,  6, 11, 12]]))

In [48]:
bos = torch.concat([x_min, y_min, x_max], -1)
x_min.shape

torch.Size([1, 3])

In [49]:
bos.shape

torch.Size([1, 9])

In [40]:
import torch 
a = torch.tensor([1,2,3,4])

In [41]:
x = a [:-1] # bỏ đi giá trị cuối cùng 
x

tensor([1, 2, 3])

In [46]:
c = a[-2:] # lấy giá trị cuối cùng 
c

tensor([3, 4])

In [43]:
v = a[1:]
v

tensor([2, 3, 4])

In [2]:
import numpy as np 
a = np.array([1 ,2 ,3])
a, a.shape

(array([1, 2, 3]), (3,))

In [8]:
b = a[]
b

array([], dtype=int32)